name: XpBottles
main: me.codedred.xpbottles.Main
author: CodedRed
version: 1.2.0
api-version: 1.13
loadbefore: [Essentials]
softdepend: [Vault]

commands:
  exp:
    description: Allows you to withdraw exp into an exp bottle!
    usage: /<command>
  xp:
    description: Allows you to use admin exp commands!
    usage: /<command>

  